// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Eo_B10GsE9_h0B7tiLjLlBqrPG6X20U',
    appId: '1:718715320122:web:a8cd660b112bcc3495c203',
    messagingSenderId: '718715320122',
    projectId: 'atomicoat-new',
    authDomain: 'atomicoat-new.firebaseapp.com',
    storageBucket: 'atomicoat-new.firebasestorage.app',
    measurementId: 'G-LF28SGXN11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZcCZbUtNcXpQvP6VNsAVLeJiLWDc4kQ',
    appId: '1:718715320122:android:45c7ea19fe9fabc895c203',
    messagingSenderId: '718715320122',
    projectId: 'atomicoat-new',
    storageBucket: 'atomicoat-new.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_Qo_mAyq0FaghI_2lD6gdvxMXWOtbw0',
    appId: '1:718715320122:ios:bd814e6e0cb1bdc695c203',
    messagingSenderId: '718715320122',
    projectId: 'atomicoat-new',
    storageBucket: 'atomicoat-new.firebasestorage.app',
    iosBundleId: 'com.example.atomicoat17thVersion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Eo_B10GsE9_h0B7tiLjLlBqrPG6X20U',
    appId: '1:718715320122:web:b5ed07a3b5408bd895c203',
    messagingSenderId: '718715320122',
    projectId: 'atomicoat-new',
    authDomain: 'atomicoat-new.firebaseapp.com',
    storageBucket: 'atomicoat-new.firebasestorage.app',
    measurementId: 'G-VXBRBF9DQC',
  );
}
